#! /bin/sh
#	$Id: update-resolv,v 1.4 2015/10/27 12:06:58 lems Exp $
#
# This overwrites the default /etc/resolv.conf file with DNS servers
# that are only reachable from within the VPN connection.
# /storage/VPN-UP will be created once the VPN connection is up, via
# the up script entry.

applied=false
while ! $applied; do
	sleep 5s
	if [ -f /storage/VPN-UP ]; then
		cat /storage/.config/vpn/resolv.conf.vpn > /etc/resolv.conf
		applied=true
	fi
done
