#! /bin/sh
#	$Id: update-resolv-no-vpn,v 1.3 2015/04/08 14:36:25 lems Exp $
#
# Update /etc/resolv.conf with alternative DNS servers.
# Basically not needed since I force them on my router anyway.

sleep 10s
cat /storage/.config/vpn/resolv.conf > /etc/resolv.conf
