#! /bin/sh
#	$Id: vpn-down,v 1.3 2015/04/29 02:43:49 lems Exp $
#
# This is run via the openvpn config file -- restore /etc/resolv.conf

rm -f /storage/VPN-UP
cat /storage/.config/vpn/resolv.conf > /etc/resolv.conf
